FROM jupyter/base-notebook:latest
USER root
# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*
USER ${NB_UID}
# Install Python packages
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install jupyterlab-spreadsheet-editor
RUN pip install jupyter_scheduler